### ISSUE TITLE
PLUGIN CONFLICT: string_helper.ts

### ISSUE THREAD

**Issue by mayurankv** [sandrofigo/obsidian-pretty-bibtex#15]
This plugin currently causes a major plugin conflict by rewriting the definition for a String and the replaceAll method (which is pretty integral) in `string_helper.ts`: https://github.com/sandrofigo/obsidian-pretty-bibtex/blob/master/string.extensions.ts. This should definitely not be done in this manner, I can't quite identify where this code is used to submit an FR but would it be possible to amend/remove it?

Thank you for your consideration.

**Comment by sandrofigo** [comment]
Thanks for bringing this up. I will look into this as soon as possible.

**Comment by sandrofigo** [comment]
@mayurankv I have removed the string extensions in release [2.0.1](https://github.com/sandrofigo/obsidian-pretty-bibtex/releases/tag/2.0.1), after updating the plugin in your vault the conflict should be resolved.

Let me know if the problem is solved.

**Comment by mayurankv** [comment]
Works perfectly now, thank you!
