### ISSUE TITLE
Support multiple Bibtex entries in a single code block

### ISSUE THREAD

**Issue by niklaswimmer** [sandrofigo/obsidian-pretty-bibtex#2]
As far as I can tell, the plugin currently does only support a single entry per code block. Writing multiple code blocks for multiple sources is tedious and imo not necessary.

I propose to change the regex that is used to extract the required values from the codeblock:

`@(?<type>.*?){\s*(?<id>.*?),(?<attributes>(?:\s*.*?\s*=\s*[{"].*[}"],?)*)\s*}`

Additionally, it will be necessary to set the regex `g` option, to match more than once (note that the `s` option is not required with the proposed regex). I guess the match function will returns some kind of array then? I am not really proficient with js/ts.

Link to regex101 loaded with the proposed regex for verification: https://regex101.com/r/D1MHvH/1

I wanted to drop this here, because I won't have time to look into it myself in the near future (and I thought someone with more experience in this field might find this is an easy change, no clue tbh xD).

**Comment by sandrofigo** [comment]
Thank you for bringing this up.

I will include this in the next version of the plugin, if I find some time to do it (probably in the next weeks/months).

If anyone can help with a PR in the meantime, that would be appreciated a lot.

**Comment by sandrofigo** [comment]
Added with 387ae6fdcde6795fc1f05c4266defb08f17cf9ba and the help of @JvJvless 

The changes will be included in the next release v2.0.0

**Comment by sandrofigo** [comment]
With the new parser there is less regex code in the plugin itself and it makes the code a lot more readable imo, but it introduced another minor issue for the ordering of fields, see #10
